namespace EpicGamesSearch;

public static class GameEngines
{
    public static List<string> Values => new List<string>()
        {
        "4A Engine",
        "A-Frame (VR)",
        "Adventure Game Interpreter",
        "Adventure Game Studio",
        "Alamo",
        "Aleph One",
        "Antiryad Gx",
        "Anura",
        "Anvil",
        "AppGameKit",
        "Ardor3D",
        "Aurora toolset",
        "Babylon.js",
        "BigWorld",
        "Blend4Web",
        "Blender Game Engine",
        "Bork3D Game Engine",
        "BRender",
        "Build engine",
        "Buildbox",
        "C4 Engine",
        "Cafu Engine",
        "CPAL3D",
        "Chrome Engine",
        "ClanLib",
        "Clausewitz",
        "Clickteam Fusion",
        "Cocos2d, Cocos2d-x, Cocos2d-html5",
        "Codea",
        "Coldstone",
        "Construct",
        "CopperCube",
        "CraftStudio",
        "Creation Engine",
        "CryEngine",
        "Crystal Tools",
        "Crystal Space",
        "Cube Engine",
        "Cube 2 Engine",
        "Dagor Engine",
        "Dark Engine",
        "Decima",
        "Defold",
        "Delta3D",
        "Dim3",
        "DimensioneX Multiplayer Engine",
        "DX Studio",
        "Dunia Engine",
        "ego",
        "Electron toolset",
        "Enforce",
        "Enigma Engine",
        "Essence Engine",
        "Exult",
        "Flare3D",
        "Flixel",
        "ForgeLight",
        "Fox Engine",
        "Freescape",
        "Frostbite",
        "Future Pinball",
        "Gamebryo",
        "Game Editor",
        "GameMaker Studio",
        "GameSalad",
        "Gamestudio",
        "Gamvas",
        "GDevelop",
        "Glacier",
        "Godot",
        "Gold Box",
        "GoldSrc",
        "HeroEngine",
        "Horde3D",
        "HPL Engine",
        "id Tech 0",
        "id Tech 1",
        "id Tech 2",
        "id Tech 2.5",
        "id Tech 3",
        "id Tech 3.5",
        "id Tech 4",
        "id Tech 4.5",
        "id Tech 5",
        "id Tech 6",
        "id Tech 7",
        "iMUSE",
        "Infinity Engine",
        "Irrlicht",
        "ioquake3",
        "Iron Engine",
        "IW engine",
        "Jade",
        "Jake2",
        "Java 3D",
        "Jedi",
        "jMonkeyEngine",
        "Kinetica",
        "Kivy (framework)",
        "LayaAir",
        "Leadwerks",
        "LibGDX",
        "LithTech",
        "Lumberyard",
        "Luminous Studio",
        "LyN",
        "LÖVE 2D",
        "M.U.G.E.N",
        "Marmalade",
        "Moai SDK",
        "MT Framework",
        "MonoGame / XNA",
        "Nebula Engine",
        "NScripter",
        "O3DE",
        "Odyssey Engine",
        "OGRE",
        "OHRRPGCE",
        "ONScripter",
        "OpenClonk",
        "OpenMW",
        "OpenSimulator",
        "ORX",
        "Panda3D",
        "Panta Rhei",
        "Phaser",
        "PhyreEngine",
        "Pico-8",
        "Pie in the Sky",
        "Pixel Game Maker MV",
        "PlayCanvas",
        "PlayN",
        "Pygame",
        "Pyrogenesis",
        "Qfusion",
        "Real Virtuality",
        "REDengine",
        "Ren'Py",
        "RenderWare",
        "RAGE",
        "Rockstar Advanced Game Engine",
        "RPG Maker",
        "SAGE",
        "SCUMM",
        "Shark 3D",
        "ShiVa",
        "Sierra's Creative Interpreter (SCI)",
        "Silent Storm engine",
        "Snowdrop",
        "Solar2D",
        "Source",
        "Spring",
        "Starling Framework",
        "Stencyl",
        "Autodesk Stingray (Bitsquid)",
        "StepMania",
        "Stratagus",
        "Stride",
        "Three.js",
        "TOSHI",
        "Truevision3D",
        "Torque3D",
        "Turbulenz",
        "Twine",
        "UbiArt Framework",
        "Unigine",
        "Unreal",
        "Unity",
        "V-Play Game Engine",
        "Vengeance Engine",
        "Vicarious Visions Alchemy",
        "Vicious Engine",
        "Virtools",
        "Vision",
        "Visual3D Game Engine",
        "Visual Pinball",
        "VRAGE",
        "Wintermute Engine",
        "World Builder",
        "WorldForge",
        "XnGine",
        "Zillions of Games",

    };
}
